### ISSUE TITLE
Gorn warning messages repeat too often.

### ISSUE THREAD

**Issue by ncombat** [ncombat/ncombat#25]
_Original author: Charles....@gmail.com (July 30, 2011 17:55:34)_

<b>What steps will reproduce the problem?</b>
1. Connect to the game.
2. Be lucky such that Gorn bases issue warnings to you.
3. Do nothing for a long time; enter no commands.

Warnings are repeated many, many times to the effect that the Gorn will open fire if I don't turn back.

One would have been sufficient.  Apparently, we need to coalesce these messages.

_Original issue: http://code.google.com/p/ncombat/issues/detail?id=25_

**Comment by lonmiller** [comment]
This is resolved - gorn checks for distance and warns one time per command cycle.
