### ISSUE TITLE
Bots are not using missiles

### ISSUE THREAD

**Issue by ncombat** [ncombat/ncombat#26]
_Original author: lonmiller@gmail.com (August 02, 2011 20:37:15)_

<b>What steps will reproduce the problem?</b>
1. Start a new game.
2. Approach to within 20000 of bot shop
3. Allow bot ship heading to become between -0.5 / 0.5

<b>What is the expected output? What do you see instead?</b>

Bot should be using missiles inside 20000 km. Bot fires laser but does not use missile.

<b>Please use labels and text to provide additional information.</b>

_Original issue: http://code.google.com/p/ncombat/issues/detail?id=26_

**Comment by lonmiller** [comment]
Resolved Issue 26 - bots now using missiles. Else if meant that if laser was used, bot skipped missile check.
