### ISSUE TITLE
Gorn damage and shield calculations incorrect 

### ISSUE THREAD

**Issue by ncombat** [ncombat/ncombat#28]
_Original author: lonmiller@gmail.com (December 01, 2011 09:14:37)_

<b>What steps will reproduce the problem?</b>
1. Engage Gorn in battle and damage Gorn base.
2. Damage shows as negative. Damage should be positive.
3. Shield power increases above 25. Shield power should be 25 max.

Example output:

 2  0&#37;  0  0      8   34.5  157.0 101451    34.5
21  0&#37; 25 25      0   50.1 -139.8 126029    50.1
22  3&#37; 25 25      0 -170.0    0.1  19385  -170.0
23  0&#37; 25 25      0  -51.9  118.2 131270   -51.9
24  0&#37; 25 25      0   -1.1  169.0 180940    -1.1
 3 13&#37; 23  0    124    0.0
  8674    4    0  0/25/ 0  0    0/  0    0/  0    0
CMDS? M22,22L2000
MISSILE HIT ON SHIELD 1 OF SHIP 22 CAUSED -10&#37; DAMAGE.
MISSILE HIT ON SHIELD 1 OF SHIP 22 CAUSED -22&#37; DAMAGE.
LASER HIT ON SHIELD 1 OF SHIP 22 CAUSED  -3&#37; DAMAGE.
 1  0&#37;  0  0      5   57.0  173.9 100221    57.0
 2  0&#37;  0  0      8   35.3  157.7 104043    35.3
21  0&#37; 25 25      0   49.2 -140.7 128337    49.2
22-33&#37; 34 34      0 -170.0    0.1  16385  -170.0
23  0&#37; 25 25      0  -50.8  119.3 132712   -50.8
24  0&#37; 25 25      0   -0.9  169.2 183887    -0.9
 3 13&#37; 23  0    124    0.0
  6074    4    0 60/23/60 60    0/  0    0/  0    0

_Original issue: http://code.google.com/p/ncombat/issues/detail?id=28_

**Comment by lonmiller** [comment]
Issue still exists-  also damage calc is wrong.
CMDS? M21,21
MISSILE HIT ON SHIELD 1 OF SHIP 21 CAUSED -38% DAMAGE.
MISSILE HIT ON SHIELD 1 OF SHIP 21 CAUSED -81% DAMAGE.
21-143% 61 61      0   86.3    0.0  18593    86.3
 3 20%  4  0      5  179.5
CMDS? L1000
SHIP 1 - BOT SHIP #3 COMMANDING, JUST APPEARED.
LASER HIT ON SHIELD 1 OF SHIP 21 CAUSED -10% DAMAGE.
21-153% 63 63      0   86.3    0.0  18663    86.3
 3 17%  4  0      5  179.5
  1/ 114.1)
  2/  59.4)
 22/-140.5)
 23/ -89.6)
 24/ -38.8)
  1865   10    0 45/21/45 35    0/  0    0/  0 1139

MESSAGE FROM GORN BASE 1 : YOU ARE TRESPASSING IN GORN SPACE. TURN BACK OR YOU WILL BE DESTROYED.


>>PWANG<< SHIP 21 LASER HIT SHIELD 1 CAUSED 18% DAMAGE.

**Comment by lonmiller** [comment]
Resolved. The gorn damage coefficient constants had been raised from the values in the base Ship types, resulting in negative damage levels.
