### ISSUE TITLE
Improve teletype to use less CPU and allow longer scrollback.

### ISSUE THREAD

**Issue by ncombat** [ncombat/ncombat#5]
_Original author: Charles....@gmail.com (November 03, 2009 12:30:54)_

Existing teletype has very short clipping area to prevent excessive CPU
usage, which is still too high.  Every character causes the teletype div to
be re-evaluated as an HTML DOM element, and it's too much for the browser.

_Original issue: http://code.google.com/p/ncombat/issues/detail?id=5_

**Comment by lonmiller** [comment]
This issue was with IE6, which was itself an issue. Other browsers do not seem to have this issue. Closing.
