### ISSUE TITLE
Implement Gorn behavior.

### ISSUE THREAD

**Issue by ncombat** [ncombat/ncombat#9]
_Original author: Charles....@gmail.com (November 03, 2009 12:47:26)_

This includes at least the following:

- Decide on Gorn characteristics, e.g.shields, blasters, heat, energy, etc.
- Develop Gorn equations for damage, heat, energy, etc.
- Decide precisely how Gorns will behave.
- Make Gorns susceptible to ship weapons by implementing onMissileHist()
and onLaserHit() in GornBase.
- Implement a BlasterCommand for Gorn blasters.
- Implement onBlasterHit() for all combatants.
- Implement GornBase.update()
- Implement Gorn command generation behavior in GornBase.completeGameCycle().

_Original issue: http://code.google.com/p/ncombat/issues/detail?id=9_

**Comment by lonmiller** [comment]
This is complete - gorn behavior and regen implemented.
